SOURCES=main.cpp \
	utility.cpp \
	program.cpp \
	material_lib.cpp \
	texture_loader.cpp \
	texture_binder.cpp \
	resource_manager.cpp \
	material.cpp \
	options.cpp \
	camera.cpp \
	fps_manager.cpp \
	object.cpp \
	shader.cpp \
	render_scene.cpp \
	devices_state.cpp \
	polygon.cpp \
	obj_loader.cpp \
	textfile.cpp

OBJS=$(patsubst %.cpp, _build/%.o, $(SOURCES))
